export const REQUEST_MYRIDES='REQUEST_MYRIDES'
export const ADD_MYRIDES='ADD_MYRIDES'
export const ERROR_MYRIDES='ERROR_MYRIDES'

export const LOCATION_TAG_ADD = 'LOCATION_TAG_ADD'
export const LOCATION_TAG_REMOVE = 'LOCATION_TAG_REMOVE'

export const BIKE_TAG_ADD = 'BIKE_TAG_ADD'
export const BIKE_TAG_REMOVE = 'BIKE_TAG_REMOVE'